---
title: "fb-dash"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plyr)
library(dplyr)
library(plotly)
library(maps)
library(Cairo)
library(sf)

#FB Data Locations for initial import
region_import <- "data/fb_region.csv"
age_import <- "data/fb_age.csv"
gender_import <- "data/fb_gender.csv"

source("src/data_import.R")

#Running data_import function to create tibbles
fb_region <- data_import(region_import)
fb_age <- data_import(age_import)
fb_gender<- data_import(gender_import)

```

Row
-----------------------------
### Gender Audiences

```{r}
plot_ly(fb_gender, 
        x = ~Gender, 
        y = ~Reach, 
        type = "bar", 
        mode = "markers",
        visible = T) %>%
  add_trace(fb_age, y = ~Impressions, visible = F) %>%
  add_trace(fb_age, y = ~`CPC (All)`, visible = F) %>%
  add_trace(fb_age, y = ~`CTR (All)`, visible = F) %>% 
  layout(
    showlegend=FALSE,
    yaxis = list(title = "Metric"),
    updatemenus = list(
      list(
        y = 1,
        x = 1,
        buttons = list(
          list(method = "restyle",
               label = "Reach",
               args = list("visible", list(TRUE, FALSE, FALSE, FALSE))),
          list(method = "restyle",
               label = "Impressions",
               args = list("visible", list(FALSE, TRUE, FALSE, FALSE))),
          list(method = "rstyle",
               label = "CPC",
               args = list("visible", list(FALSE, FALSE, TRUE, FALSE))),
          list(method = "restyle",
               label = "CTR",
               args = list("visible", list(FALSE, FALSE, FALSE, TRUE)))
        ))))
```

### Age Audiences

```{r}
plot_ly(fb_age, 
        x = ~Age, 
        y = ~Reach, 
        type = "bar", 
        mode = "markers",
        visible = T) %>%
  add_trace(fb_age, y = ~Impressions, visible = F) %>%
  add_trace(fb_age, y = ~`CPC (All)`, visible = F) %>%
  add_trace(fb_age, y = ~`CTR (All)`, visible = F) %>% 
  layout(
    showlegend=FALSE,
    yaxis = list(title = "Metric"),
    updatemenus = list(
      list(
        y = 1,
        x = 1,
        buttons = list(
          list(method = "restyle",
               label = "Reach",
               args = list("visible", list(TRUE, FALSE, FALSE, FALSE))),
          list(method = "restyle",
               label = "Impressions",
               args = list("visible", list(FALSE, TRUE, FALSE, FALSE))),
          list(method = "rstyle",
               label = "CPC",
               args = list("visible", list(FALSE, FALSE, TRUE, FALSE))),
          list(method = "restyle",
               label = "CTR",
               args = list("visible", list(FALSE, FALSE, FALSE, TRUE)))
        ))))
```

Row {.tabset} 
------------------------------

### Impressions Overview
```{r}
#Preparing mapping info of US
us_states <- map_data("state")
us_map <- map_data("usa")

#adjusting fb_region tibble to match with us map data
fb_region_low <- fb_region %>% 
  mutate(Region = tolower(Region)) %>% 
  mutate(Region=replace(Region, Region == "washington, district of columbia", "district of columbia")) %>% 
  rename(region = Region)

#Joining us map data and fb_region 
region_map <- left_join(us_states, fb_region_low, by = "region")

impressions_map <- ggplot(
  data = region_map, 
  mapping = aes(
    x = long, 
    y = lat,
    group = group, 
    text1 = region,
    text2 = Impressions,
    text3 = Reach,
    text4 = `CPC (All)`,
    text5 = `CTR (All)`)) +
  geom_polygon(
    color = "black", 
    fill = "gray") +
  geom_polygon(data = region_map, 
               aes(fill = Impressions),
               color = "white") +
  coord_quickmap() +
  theme_void()

ggplotly(
  p = impressions_map,
 tooltip = c("text1","text2", "text3", "text4", "text5"))
```

### Reach Overview
```{r}
#Joining us map data and fb_region 
reach_map <- ggplot(
  data = region_map, 
  mapping = aes(
    x = long, 
    y = lat,
    group = group, 
    text1 = region,
    text2 = Impressions,
    text3 = Reach,
    text4 = `CPC (All)`,
    text5 = `CTR (All)`)) +
  geom_polygon(
    color = "black", 
    fill = "gray") +
  geom_polygon(data = region_map, 
               aes(fill = Reach),
               color = "white") +
  coord_quickmap() +
  theme_void()

reach_map
```

### CPC Overview
```{r}
#Joining us map data and fb_region 
cpc_map <- ggplot(
  data = region_map, 
  mapping = aes(
    x = long, 
    y = lat,
    group = group, 
    text1 = region,
    text2 = Impressions,
    text3 = Reach,
    text4 = `CPC (All)`,
    text5 = `CTR (All)`)) +
  geom_polygon(
    color = "black", 
    fill = "gray") +
  geom_polygon(data = region_map, 
               aes(fill = `CPC (All)`),
               color = "white") +
  coord_quickmap() +
  theme_void()

cpc_map
```

### CTR Overview
```{r}
#Joining us map data and fb_region 
ctr_map <- ggplot(
  data = region_map, 
  mapping = aes(
    x = long, 
    y = lat,
    group = group, 
    text1 = region,
    text2 = Impressions,
    text3 = Reach,
    text4 = `CPC (All)`,
    text5 = `CTR (All)`)) +
  geom_polygon(
    color = "black", 
    fill = "gray") +
  geom_polygon(data = region_map, 
               aes(fill = `CTR (All)`),
               color = "white") +
  coord_quickmap() +
  theme_void()

ctr_map
```